-- Breeze FALSO para scripts/probar-migraciones.mjs: las tablas de public que
-- leen las vistas hub.rmm_* (20261006_rmm.sql), con sus columnas de verdad
-- (los enums de Breeze, como text). Sacado del proyecto el 2026-09-27; al
-- subir de versión Breeze, regenerarlo si cambian las columnas que se leen.
-- NO es una migración: solo lo carga el arnés en su Postgres desechable.
create table public.alerts (id uuid, rule_id uuid, device_id uuid, org_id uuid, status text, severity text, title character varying(500), message text, context jsonb, triggered_at timestamp without time zone, acknowledged_at timestamp without time zone, acknowledged_by uuid, resolved_at timestamp without time zone, resolved_by uuid, resolution_note text, suppressed_until timestamp without time zone, created_at timestamp without time zone, config_policy_id uuid, config_item_name character varying(200), dismissed_at timestamp without time zone, dismissed_by uuid);
create table public.device_commands (id uuid, device_id uuid, type character varying(50), payload jsonb, status character varying(20), created_by uuid, created_at timestamp without time zone, executed_at timestamp without time zone, completed_at timestamp without time zone, result jsonb, target_role character varying(20));
create table public.device_disks (id uuid, device_id uuid, mount_point character varying(255), device character varying(255), fs_type character varying(50), total_gb real, used_gb real, free_gb real, used_percent real, health character varying(50), updated_at timestamp without time zone, org_id uuid);
create table public.device_hardware (device_id uuid, cpu_model character varying(255), cpu_cores integer, cpu_threads integer, ram_total_mb integer, disk_total_gb integer, gpu_model character varying(255), serial_number character varying(100), manufacturer character varying(255), model character varying(255), bios_version character varying(100), updated_at timestamp without time zone, org_id uuid, motherboard_manufacturer character varying(255), motherboard_product character varying(255), motherboard_version character varying(255), partner_export_updated_at timestamp(3) without time zone);
create table public.device_metrics (device_id uuid, "timestamp" timestamp without time zone, cpu_percent real, ram_percent real, ram_used_mb integer, disk_percent real, disk_used_gb real, network_in_bytes bigint, network_out_bytes bigint, bandwidth_in_bps bigint, bandwidth_out_bps bigint, interface_stats jsonb, process_count integer, custom_metrics jsonb, disk_activity_available boolean, disk_read_bytes bigint, disk_write_bytes bigint, disk_read_bps bigint, disk_write_bps bigint, disk_read_ops bigint, disk_write_ops bigint, org_id uuid);
create table public.device_network (id uuid, device_id uuid, interface_name text, mac_address character varying(64), ip_address character varying(45), ip_type character varying(4), is_primary boolean, public_ip character varying(45), updated_at timestamp without time zone, org_id uuid);
create table public.device_patches (id uuid, device_id uuid, patch_id uuid, status text, installed_at timestamp without time zone, installed_version character varying(100), last_checked_at timestamp without time zone, failure_count integer, last_error text, rollback_available boolean, created_at timestamp without time zone, updated_at timestamp without time zone, org_id uuid);
create table public.device_software (id uuid, device_id uuid, name character varying(500), version character varying(100), publisher character varying(255), install_date date, install_location text, is_system boolean, updated_at timestamp without time zone);
create table public.devices (id uuid, org_id uuid, site_id uuid, agent_id character varying(64), agent_token_hash character varying(64), mtls_cert_serial_number character varying(128), mtls_cert_expires_at timestamp without time zone, mtls_cert_issued_at timestamp without time zone, mtls_cert_cf_id character varying(128), quarantined_at timestamp without time zone, quarantined_reason character varying(255), hostname character varying(255), display_name character varying(255), os_type text, os_version character varying(100), os_build character varying(100), architecture character varying(20), agent_version character varying(50), status text, last_seen_at timestamp without time zone, enrolled_at timestamp without time zone, enrolled_by uuid, tags text[], custom_fields jsonb, created_at timestamp without time zone, updated_at timestamp without time zone, device_role character varying(30), device_role_source character varying(20), management_posture jsonb, last_user character varying(255), uptime_seconds integer, tcc_permissions jsonb, is_headless boolean, desktop_access jsonb, token_issued_at timestamp with time zone, previous_token_hash character varying(64), previous_token_expires_at timestamp with time zone, watchdog_status text, watchdog_last_seen timestamp without time zone, watchdog_version character varying(50), helper_token_hash character varying(64), helper_token_issued_at timestamp with time zone, previous_helper_token_hash character varying(64), previous_helper_token_expires_at timestamp with time zone, watchdog_token_hash character varying(64), watchdog_token_issued_at timestamp with time zone, previous_watchdog_token_hash character varying(64), previous_watchdog_token_expires_at timestamp with time zone, main_agent_silent_since timestamp with time zone, agent_token_suspended_at timestamp without time zone, agent_token_suspended_reason character varying(100), last_seen_ip character varying(45), pending_reboot boolean, is_virtual boolean, virtualization_platform character varying(30), battery_status jsonb, agent_server_url character varying(512), active_vpns jsonb, link_group_id uuid, link_group_role character varying(16), enrollment_ip character varying(45), partner_export_updated_at timestamp(3) without time zone, helper_lifecycle_mode character varying(20), pending_token_hash character varying(64), pending_watchdog_token_hash character varying(64), pending_helper_token_hash character varying(64), pending_token_expires_at timestamp with time zone, outbound_network_policy_version integer, backup_version character varying(50), agent_edition character varying(20), migration_required boolean, uninstall_intent_at timestamp with time zone, possible_replacement_of_device_id uuid, is_ephemeral boolean);
create table public.organizations (id uuid, partner_id uuid, name character varying(255), slug character varying(100), type text, status text, max_devices integer, settings jsonb, sso_config jsonb, contract_start timestamp without time zone, contract_end timestamp without time zone, billing_contact jsonb, created_at timestamp without time zone, updated_at timestamp without time zone, deleted_at timestamp without time zone, tax_id character varying(100), tax_exempt boolean, tax_rate numeric(8,5), billing_address_line1 character varying(255), billing_address_line2 character varying(255), billing_address_city character varying(120), billing_address_region character varying(120), billing_address_postal_code character varying(40), billing_address_country character(2), partner_export_updated_at timestamp(3) without time zone, offboarding_started_at timestamp with time zone);
create table public.patches (id uuid, source text, external_id character varying(255), title character varying(500), description text, severity text, category character varying(100), os_types text[], os_versions text[], architecture text[], release_date date, kb_article_url text, supersedes text[], superseded_by text, requires_reboot boolean, download_url text, download_size_mb integer, install_command text, uninstall_command text, detect_script text, metadata jsonb, created_at timestamp without time zone, updated_at timestamp without time zone, vendor character varying(255), package_id character varying(256), cve_ids text[], version character varying(64));
create table public.remote_sessions (id uuid, device_id uuid, user_id uuid, type text, status text, webrtc_offer text, webrtc_answer text, ice_candidates jsonb, started_at timestamp without time zone, ended_at timestamp without time zone, duration_seconds integer, bytes_transferred bigint, recording_url text, created_at timestamp without time zone, error_message text, org_id uuid);
create table public.script_executions (id uuid, script_id uuid, device_id uuid, triggered_by uuid, trigger_type text, parameters jsonb, status text, started_at timestamp without time zone, completed_at timestamp without time zone, exit_code integer, stdout text, stderr text, error_message text, created_at timestamp without time zone, org_id uuid, automation_run_id uuid);
create table public.scripts (id uuid, org_id uuid, name character varying(255), description text, category character varying(100), os_types text[], language text, content text, parameters jsonb, timeout_seconds integer, run_as text, is_system boolean, version integer, created_by uuid, created_at timestamp without time zone, updated_at timestamp without time zone, exit_code_severity_mapping jsonb, deleted_at timestamp without time zone, partner_id uuid);
create table public.security_status (id uuid, device_id uuid, provider text, provider_version character varying(50), definitions_version character varying(100), definitions_date timestamp without time zone, real_time_protection boolean, last_scan timestamp without time zone, last_scan_type character varying(50), threat_count integer, firewall_enabled boolean, encryption_status character varying(50), encryption_details jsonb, local_admin_summary jsonb, password_policy_summary jsonb, gatekeeper_enabled boolean, updated_at timestamp without time zone, org_id uuid);
create table public.sites (id uuid, org_id uuid, name character varying(255), address jsonb, timezone character varying(50), contact jsonb, settings jsonb, created_at timestamp without time zone, updated_at timestamp without time zone, partner_export_updated_at timestamp(3) without time zone);
create table public.software_inventory (id uuid, device_id uuid, catalog_id uuid, name character varying(500), version character varying(100), vendor character varying(200), install_date date, install_location text, uninstall_string text, is_managed boolean, last_seen timestamp without time zone, file_hash character varying(128), hash_algorithm character varying(10), org_id uuid);
create table public.users (id uuid primary key, email varchar, name varchar);
