-- ════════════════════════════════════════════════════════════════════════
-- Paridad bloque 6 · tanda 4: avisos push en el dispositivo y Feedback.
--
-- 1. hub.push_suscripciones: los navegadores/PWA que han aceptado los avisos
--    (Web Push con las claves VAPID PROPIAS del hub, secrets VAPID_*). Como en
--    la app (push_subscriptions), el registro lo hace la función `push` con la
--    service key: un mismo dispositivo cambia de dueño al cambiar de sesión, y
--    eso la RLS del navegador no lo deja. Desde el navegador solo se LEEN las
--    propias. Se borran solas cuando el servicio de push dice que ya no existen.
-- 2. hub.feedback: lo que el equipo cuenta del hub (fallo, mejora, idea), con
--    el contexto que el front recoge solo (pantalla, versión, entorno, últimos
--    errores). «Pasar a Claude» la deja en `claude`: el trabajador de Claude la
--    toma por el conector MCP (feedback_*), la arregla y la cierra con lo hecho.
--    Sin issues de GitHub ni token en el navegador (decisión de Fran, bloque 6).
-- 3. pg_cron «trabajos en ~1 hora»: la función `push` no hace NADA mientras la
--    agenda sea de la app (avisa la app, y avisar desde los dos duplicaría).
-- ════════════════════════════════════════════════════════════════════════

create table if not exists hub.push_suscripciones (
  id          uuid primary key default gen_random_uuid(),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  usuario_id  uuid not null,                       -- hub.usuarios
  endpoint    text not null unique check (length(endpoint) <= 2000),
  p256dh      text not null,
  auth        text not null,
  dispositivo text,                                -- user agent recortado
  ultimo_ok   timestamptz,
  ultimo_error text
);
create index if not exists push_suscripciones_usuario_idx on hub.push_suscripciones (usuario_id);

drop trigger if exists tocar_updated_at on hub.push_suscripciones;
create trigger tocar_updated_at before update on hub.push_suscripciones
  for each row execute function hub.tocar_updated_at();

alter table hub.push_suscripciones enable row level security;
grant select on hub.push_suscripciones to authenticated;
grant all on hub.push_suscripciones to service_role;

drop policy if exists propias on hub.push_suscripciones;
create policy propias on hub.push_suscripciones for select to authenticated
  using ((select hub.es_usuario()) and usuario_id = (select (hub.usuario_actual()).id));
-- Sin auditoría: son claves de un navegador, no datos de negocio.

create table if not exists hub.feedback (
  id           uuid primary key default gen_random_uuid(),
  numero       integer generated by default as identity,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  tipo         text not null default 'bug' check (tipo in ('bug','mejora','idea')),
  descripcion  text not null check (length(trim(descripcion)) > 2 and length(descripcion) <= 8000),
  seccion      text,                               -- id de la pantalla
  ruta         text,                               -- el hash en el que estaba
  estado       text not null default 'nueva'
               check (estado in ('nueva','claude','en_curso','hecha','descartada')),
  autor_id     uuid,                               -- hub.usuarios (lo pone la base)
  autor_nombre text,
  contexto     jsonb not null default '{}'::jsonb, -- versión, entorno, errores…
  notas        text,                               -- del admin, para Claude
  pasada_at    timestamptz,                        -- cuándo se pasó a Claude
  tomada_at    timestamptz,
  terminada_at timestamptz,
  resultado    text                                -- lo que hizo Claude (markdown)
);
create unique index if not exists feedback_numero_idx on hub.feedback (numero);
create index if not exists feedback_estado_idx on hub.feedback (estado, created_at);

drop trigger if exists tocar_updated_at on hub.feedback;
create trigger tocar_updated_at before update on hub.feedback
  for each row execute function hub.tocar_updated_at();

-- El autor lo pone la base (no se fía del navegador).
create or replace function hub.feedback_antes()
returns trigger language plpgsql set search_path = hub as $fn$
declare u hub.usuarios;
begin
  if tg_op = 'INSERT' and coalesce(auth.jwt()->>'role', '') <> 'service_role' then
    u := hub.usuario_actual();
    new.autor_id := u.id; new.autor_nombre := u.nombre; new.estado := 'nueva';
    new.pasada_at := null; new.tomada_at := null; new.terminada_at := null; new.resultado := null;
  end if;
  if tg_op = 'UPDATE' and new.estado = 'claude' and old.estado is distinct from 'claude' then new.pasada_at := now(); end if;
  return new;
end
$fn$;
drop trigger if exists feedback_antes on hub.feedback;
create trigger feedback_antes before insert or update on hub.feedback
  for each row execute function hub.feedback_antes();

alter table hub.feedback enable row level security;
grant select, insert, update, delete on hub.feedback to authenticated;
grant all on hub.feedback to service_role;

-- Leer: el admin todo; el resto lo suyo.
drop policy if exists leer on hub.feedback;
create policy leer on hub.feedback for select to authenticated
  using ((select hub.es_admin()) or ((select hub.es_usuario()) and autor_id = (select (hub.usuario_actual()).id)));
drop policy if exists contar on hub.feedback;
create policy contar on hub.feedback for insert to authenticated with check ((select hub.es_usuario()));
-- Gestionar (estado, notas, pasar a Claude, borrar): solo admin.
drop policy if exists gestionar on hub.feedback;
create policy gestionar on hub.feedback for update to authenticated using ((select hub.es_admin())) with check ((select hub.es_admin()));
drop policy if exists borrar on hub.feedback;
create policy borrar on hub.feedback for delete to authenticated using ((select hub.es_admin()));

select hub.auditar('feedback');

-- Trabajos en ~1 hora (como send-push-notifications de la app). La función
-- comprueba ella misma que la agenda sea ya del hub.
select cron.schedule('hub-push-proximos', '*/15 * * * *', $$select hub.lanzar_funcion('push', '{"accion":"proximos"}')$$);
